### ISSUE TITLE
Swift日志打印有问题

### ISSUE THREAD

**Issue by charleszhao888888** [TencentCloud/TPNS-iOS-CocoaPods#2]
![image](https://user-images.githubusercontent.com/13135925/138207336-13fe2f20-1587-4e0a-b846-5063f3d52679.png)
上面的代理方法回调的字符串都是`[TPNS]  %@`
![image](https://user-images.githubusercontent.com/13135925/138207300-8839c882-6467-441c-97c4-ef706bf3b07e.png)

**Comment by rockzuo-104** [comment]
请使用XGPush->setEnableDebug
